[server]
headless = true
port = 8501

[client]
showSidebarNavigation = true

[theme]

primaryColor = "#4CAF50"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F0F0"
textColor = "#000000"
font = "sans serif"
